version: "3"
services:
  pomerium:
    image: pomerium/pomerium:v0.14.2
    environment:
      # Generate new secret keys. e.g. `head -c32 /dev/urandom | base64`
      - COOKIE_SECRET=V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
    volumes:
      # Mount your domain's certificates : https://www.pomerium.io/docs/reference/certificates
      - ./_wildcard.localhost.pomerium.io.pem:/pomerium/cert.pem:ro
      - ./_wildcard.localhost.pomerium.io-key.pem:/pomerium/privkey.pem:ro

      # Mount your config file : https://www.pomerium.io/docs/reference/reference/
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443

  # https://verify.corp.beyondperimeter.com --> Pomerium --> http://verify
  verify:
    image: pomerium/verify:v0.0.4
    expose:
      - 80

  codeserver:
    image: codercom/code-server:3.10.1
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./code-server:/home/coder/project
    command: --auth none --disable-telemetry /home/coder/project
